### ISSUE TITLE
PHPmailer \  Cannot signup page cannot load after enter user detail

### ISSUE THREAD

**Issue by azartheen** [Subhajit25Mondal/hashtag.io#6]
if it is need to load or signup with my local mail ID(Hoster mail id)

my SQL connection is good and data transfer successful but when I create new user it gives error

**Comment by rwoloszyn** [comment]
The issue is here: config/class/PHPMailerAutoload.php on line 45

**Comment by Adityak1998** [comment]
> 

How to fix it
